/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from '../common';

export declare namespace Marketplace {
  export type ItemStruct = {
    id: BigNumberish;
    seller: AddressLike;
    buyer: AddressLike;
    name: string;
    description: string;
    imageUrl: string;
    price: BigNumberish;
    sold: boolean;
  };

  export type ItemStructOutput = [
    id: bigint,
    seller: string,
    buyer: string,
    name: string,
    description: string,
    imageUrl: string,
    price: bigint,
    sold: boolean,
  ] & {
    id: bigint;
    seller: string;
    buyer: string;
    name: string;
    description: string;
    imageUrl: string;
    price: bigint;
    sold: boolean;
  };
}

export interface MarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'buyItem'
      | 'getAllItems'
      | 'getItemsByBuyer'
      | 'itemCount'
      | 'items'
      | 'listItem',
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: 'ItemListed' | 'ItemSold'): EventFragment;

  encodeFunctionData(functionFragment: 'buyItem', values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: 'getAllItems', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getItemsByBuyer', values: [AddressLike]): string;
  encodeFunctionData(functionFragment: 'itemCount', values?: undefined): string;
  encodeFunctionData(functionFragment: 'items', values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: 'listItem',
    values: [string, string, string, BigNumberish],
  ): string;

  decodeFunctionResult(functionFragment: 'buyItem', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getAllItems', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getItemsByBuyer', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'itemCount', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'items', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'listItem', data: BytesLike): Result;
}

export namespace ItemListedEvent {
  export type InputTuple = [
    id: BigNumberish,
    seller: AddressLike,
    name: string,
    price: BigNumberish,
  ];
  export type OutputTuple = [id: bigint, seller: string, name: string, price: bigint];
  export interface OutputObject {
    id: bigint;
    seller: string;
    name: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ItemSoldEvent {
  export type InputTuple = [
    id: BigNumberish,
    buyer: AddressLike,
    seller: AddressLike,
    price: BigNumberish,
  ];
  export type OutputTuple = [id: bigint, buyer: string, seller: string, price: bigint];
  export interface OutputObject {
    id: bigint;
    buyer: string;
    seller: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Marketplace extends BaseContract {
  connect(runner?: ContractRunner | null): Marketplace;
  waitForDeployment(): Promise<this>;

  interface: MarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  buyItem: TypedContractMethod<[_id: BigNumberish], [void], 'payable'>;

  getAllItems: TypedContractMethod<[], [Marketplace.ItemStructOutput[]], 'view'>;

  getItemsByBuyer: TypedContractMethod<
    [_buyer: AddressLike],
    [Marketplace.ItemStructOutput[]],
    'view'
  >;

  itemCount: TypedContractMethod<[], [bigint], 'view'>;

  items: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, string, bigint, boolean] & {
        id: bigint;
        seller: string;
        buyer: string;
        name: string;
        description: string;
        imageUrl: string;
        price: bigint;
        sold: boolean;
      },
    ],
    'view'
  >;

  listItem: TypedContractMethod<
    [_name: string, _description: string, _imageUrl: string, _price: BigNumberish],
    [void],
    'nonpayable'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(
    nameOrSignature: 'buyItem',
  ): TypedContractMethod<[_id: BigNumberish], [void], 'payable'>;
  getFunction(
    nameOrSignature: 'getAllItems',
  ): TypedContractMethod<[], [Marketplace.ItemStructOutput[]], 'view'>;
  getFunction(
    nameOrSignature: 'getItemsByBuyer',
  ): TypedContractMethod<[_buyer: AddressLike], [Marketplace.ItemStructOutput[]], 'view'>;
  getFunction(nameOrSignature: 'itemCount'): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(nameOrSignature: 'items'): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, string, bigint, boolean] & {
        id: bigint;
        seller: string;
        buyer: string;
        name: string;
        description: string;
        imageUrl: string;
        price: bigint;
        sold: boolean;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'listItem',
  ): TypedContractMethod<
    [_name: string, _description: string, _imageUrl: string, _price: BigNumberish],
    [void],
    'nonpayable'
  >;

  getEvent(
    key: 'ItemListed',
  ): TypedContractEvent<
    ItemListedEvent.InputTuple,
    ItemListedEvent.OutputTuple,
    ItemListedEvent.OutputObject
  >;
  getEvent(
    key: 'ItemSold',
  ): TypedContractEvent<
    ItemSoldEvent.InputTuple,
    ItemSoldEvent.OutputTuple,
    ItemSoldEvent.OutputObject
  >;

  filters: {
    'ItemListed(uint256,address,string,uint256)': TypedContractEvent<
      ItemListedEvent.InputTuple,
      ItemListedEvent.OutputTuple,
      ItemListedEvent.OutputObject
    >;
    ItemListed: TypedContractEvent<
      ItemListedEvent.InputTuple,
      ItemListedEvent.OutputTuple,
      ItemListedEvent.OutputObject
    >;

    'ItemSold(uint256,address,address,uint256)': TypedContractEvent<
      ItemSoldEvent.InputTuple,
      ItemSoldEvent.OutputTuple,
      ItemSoldEvent.OutputObject
    >;
    ItemSold: TypedContractEvent<
      ItemSoldEvent.InputTuple,
      ItemSoldEvent.OutputTuple,
      ItemSoldEvent.OutputObject
    >;
  };
}
